# -------- Stage 1: Build --------
FROM maven:3.9-eclipse-temurin-22 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# -------- Stage 2: Run --------
FROM openjdk:22-jdk-slim
WORKDIR /app
COPY --from=build /app/target/e-commerce-pack.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
